### PR TITLE
Feature/possibility to get all response data

### PR DESCRIPTION
**Pull request by xsuchy09**
*add - Potvrzeni - create in Dispatcher from response
*add - PotvrzeniTest
*edit - php.ini - required extensions
*edit - .gitignore - ignore output of tests

### CODE REVIEW

**Comment by xsuchy09** [comment]
This is needed to get `dat_prij` from EET. So I prepared whole Potvrzeni object with yours warnings array.

**Comment by xsuchy09** [comment]
I think `send` method should return whole `Potvrzeni` object but because of back compatibility I left there just `fik` and developer can get `Potvrzeni` via `getPotvrzeni` method. I think that this should change in new major version with huge incompatbility warning.

**Comment by filipsedivy** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/Dispatcher.php  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/filipsedivy/PHP-EET/pullRequest?prid=5194711&bid=17037170)

**Comment by filipsedivy** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/Dispatcher.php  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/filipsedivy/PHP-EET/pullRequest?prid=5194711&bid=17037170)

**Comment by xsuchy09** [comment]
Any update with this functionality?

**Comment by filipsedivy** [comment]
Unfortunately, I'm currently busy developing open-source. In case you need a change for your own use, create a fork and make changes in your repository.

**Comment by filipsedivy** [comment]
Please do not change the name of the namespace and keep the original.

**Comment by xsuchy09** [comment]
I am changing it in own fork as you wrote - to make new updated library. This was just connected ... but now closed, so ...

**Comment by filipsedivy** [comment]
Make changes in your fork, but don't create a pull request.

**Pull request closed without merging**
